<?php $data=array (
  'adult' => 'Да',
  'name' => 'Полина',
  'tel' => '+7 (896) 008-68-0',
  'sex' => 'Женщина',
  'service-0' => 'Деньги под залог',
  'service-1' => 'Продажа',
  'about' => 'Взис 23',
  'adult-header' => 'Вам есть 18 лет?',
  'name-header' => 'Ваше имя',
  'tel-header' => 'Номер телефона',
  'sex-header' => 'Укажите ваш пол',
  'service-header' => 'Какими нашими услугами вы пользуетесь?',
  'about-header' => 'О себе',
); ?>